### ISSUE TITLE
shap import fails with current shap from pip

### ISSUE THREAD

**Issue by ntrost-targ** [xydrolase/shap4j-data-converter#1]
Hi, just wanted to say that the data converter sadly fails to execute 
with the following message while current shap is installed from pip.
do i need to get a specific version or so to get it running?

bests,
Nikolaus

```shap4jconv model.pkl 
Traceback (most recent call last):
  File "/usr/local/bin/shap4jconv", line 4, in <module>
    __import__('pkg_resources').run_script('shap4j-data-converter==0.0.2', 'shap4jconv')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1470, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.8/dist-packages/shap4j_data_converter-0.0.2-py3.8.egg/EGG-INFO/scripts/shap4jconv", line 5, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.8/dist-packages/shap4j_data_converter-0.0.2-py3.8.egg/shap4jconv/__init__.py", line 8, in <module>
ModuleNotFoundError: No module named 'shap.explainers.tree'```

**Comment by ntrost-targ** [comment]
just noticed shap switched from .tree to _tree - so switching to `from shap.explainers._tree import TreeEnsemble` in `__init__.py` does the trick :)
